### ISSUE TITLE
Create a way to escape the assigned station

### ISSUE THREAD

**Issue by alexanderson1993** [Thorium-Sim/thorium-nova#146]
**Is your feature request related to a problem? Please describe.**

Once a client is assigned to a station, there's no easy way for them to back out and assign themselves to a new station.

**Describe the solution you'd like**

The escape key is probably good enough. Either have it open up a menu with a button to remove the station assignment, or just have the escape key take them back immediately.

An alternative would be having an "Unassign" button on the login screen, so the user would log out and then unassign themselves from the station.

**Comment by astrolamb-gaming** [comment]
Unless the escape key is needed for something else, it's a very common keybind for opening some sort of options menu, and maintaining a common keybind is a big deal with onboarding new players, so that would be my preference.
