### ISSUE TITLE
Officers Log Card

### ISSUE THREAD

**Issue by alexanderson1993** [Thorium-Sim/thorium-nova#148]
**Is your feature request related to a problem? Please describe.**

It would be great if crew members could write about what they are doing during their mission. The officers log could serve as scratch paper, a journal, and a way to remember their experiences later on.

Eventually, this could integrate with their Thorium Nova account, but that feature can come later.

- [ ] Integrate Officers Log with the users Thorium Nova account.

**Describe the solution you'd like**

Officer log entries will be stored on the Flight Client, which means they won't be shared between multiple clients, such as if a single person is signed in to multiple computers. It might be possible to do this by storing the officer log entries separate from the flight client and keying them by the Thorium Account ID, but that isn't necessary right now.

The date should be stored, but anywhere it is shown in the controls should display the date with [beat time](http://gwil.co/internet-time/). See the screenshots below for ideas about the card and core.

**Additional context**

<img width="809" alt="Screen Shot 2021-12-07 at 6 51 50 PM" src="https://user-images.githubusercontent.com/6558157/145124012-c89cc233-e2b9-4baa-a838-a6fabc632432.png">
<img width="270" alt="Screen Shot 2021-12-07 at 6 52 08 PM" src="https://user-images.githubusercontent.com/6558157/145124013-f5c280e0-d370-48fe-a90b-540aea449347.png">

**Comment by Froginator45** [comment]
Maybe not the best solution, but you could set it up so that, when creating the flight, you define how many stations and you also define what stations are being "shared" by a single person. Thorium would then only include the officer's log on a single station among the shared stations. Or know what stations to share the log across. I don't know if there are other cards that would be useful for a setup like that or not. But if there are others that would be useful only once among the shared stations, then it might be something to consider.

**Comment by alexanderson1993** [comment]
I like your thinking, but I think it would be a lot of extra effort. One of the best unintentional features of Thorium Nova and Classic is that you can run any station on as many computers as you want. I don't want to make assumptions about how folks will be running their simulators and how many stations they'll duplicate across multiple clients, and having them configure it for every flight would be super tedious.

I _think_ having a single person use multiple clients is unlikely given the nature of Thorium Nova. So I think this is enough of an edge case that we can just ignore it and expect users to only write their officer log on a single computer.
