### ISSUE TITLE
Ship Map - Create Backend fixtures and API for storing deck nodes and edges

### ISSUE THREAD

**Issue by alexanderson1993** [Thorium-Sim/thorium-nova#164]
### Discussed in https://github.com/Thorium-Sim/thorium-nova/discussions/161

<div type='discussions-op-text'>

<sup>Originally posted by **alexanderson1993** January  3, 2022</sup>
### Graph Nodes / Rooms

The purpose of the deck map is to allow entities to travel throughout the ship. Knowing where to move can't be done with an SVG alone. A graph of nodes is also required. Nodes represent places that these entities can travel, including junctions in hallways, turbo lifts for traveling between decks, and rooms.

Nodes are overlayed on top of the SVG layers and created using an in-app editor, which is described below.

Rooms are special nodes which have some extra features.

Rooms can be named, which lets the crew see what the room is for, have the room included in a list, and let the crew search for rooms by name.

Rooms can also be given icons, which are PNGs or SVGs. Rooms without icons will have a generic icon.

Rooms are assigned a radius. This represents the relative area that the room occupies on the ship map. When a crew member is inside a room, they'll be able to move about the room within that radius which makes it appear more realistic.

Finally, rooms have system assignments, which connects that room with a specific system. For example, cargo can be transferred between rooms. Rooms with the "probe launcher" assignment will allow probe casings in that room to be used for probe construction. Multiple systems can be assigned. Rooms without specific icons might be able to use an icon associated with the assigned system.

### Edges

Edges complete the graph by connecting nodes together. They can connect nodes on the same deck, or connect nodes between decks. Only one edge can connect two nodes, but nodes can have many edges. 

Edges can be given weights, which change the speed that entities traverse that edge by multiplying the entities speed by the weight. By default, the weight is 1. Higher weights make the entities move slower; lower weights move entities faster.

## Editing the Ship Map

Creating and editing the ship map is a simple process:

...

- Next, nodes are added. An editor palette allows configuring the node properties, and the node can be dragged around to change its position. 
- Finally edges are added between nodes. Clicking and dragging with the edge tool allows edges to easily be created. A "Add Edge" button allows edges to be created between decks without clicking and dragging. Edges can be selected to change the weight.
</div>

**Comment by Lilith-NightRose** [comment]
I wonder if it would be most effective to specify a format for specifying the node/edge graph and its relationship with the SVG file. That way the map editor and the server functionality involving the map could be implemented separately.

**Comment by Lilith-NightRose** [comment]
looking through different options for previous implementation of the kind of thing that needs to be done here, I wonder if a shapefile could be used to specify nodes and edges? While obviously,  shapefiles are typically used to store earth-based geospatial data, but the basic concept (vectors, with additional reference data and associated attributes) seems to be parallel to what is being specified here.

**Comment by alexanderson1993** [comment]
> I wonder if a shapefile could be used

After taking a look at it, I'm not sure this is the way to go. I do want to make it possible to write plugins outside of the Thorium Nova software, but I would prefer the file formats involved be text-based so you can edit them with a plain text editor. Shapefiles are binary formats, so you would need a separate program to edit them anyway.

It seems like the shape file specification is mostly used for defining vectors, filling the same purpose as the SVG. To include attributes, you need to have a separate file. That starts getting a little messy.

At the end of the day, there will be a format of some kind for specifying the node/edge graph - it's just a question of whether it's an existing standard (like GraphML, Netdraw VNA, etc - there's a nice list of examples here: https://gephi.org/users/supported-graph-formats/) or we make up our own format.

Given that
- We need these node/edge graphs to line up perfectly with the SVG
- Nodes need to have labels and attributes, like the icon URL, the radius, and properties about what the room is capable of
- Edges need to have weights and attributes, like what kind of entity can traverse the edge (Jeffries tubes vs cargo lanes vs normal hallways), whether the edge is open or closed (doors and bulkheads) etc.
- Edges also need to connect cross-deck, which means being able to connect two separate graphs together.

I think our own home-grown format will serve our purposes best.
