### ISSUE TITLE
Star Map - Create Backend definitions and APIs for planets and moons

### ISSUE THREAD

**Issue by alexanderson1993** [Thorium-Sim/thorium-nova#176]

**Comment by alexanderson1993** [comment]
Any progress on this? If not, I would love to take over and finish it up so we can continue making progress on the star map.

**Comment by tannerchamb** [comment]
Yeah! I've made progress, but it's going slower than I'd like. I can push what I have if you'd like to take over on it.

**Comment by alexanderson1993** [comment]
Excellent. That would be great.
