### ISSUE TITLE
Sign up path broken fro app

### ISSUE THREAD

**Issue by miketweaver** [Thorium-Sim/thorium-nova#198]
**Describe the bug**
When you try to sign into the app in the top right, it asks for an account. If you don't have an account you have the ability to signup. Once you sign up, it just sits there and the app sits at "Verifying..."

**To Reproduce** Steps to reproduce the behavior:

Try to sign in:
![image](https://user-images.githubusercontent.com/5581855/150029628-3cf45a26-5e45-457e-b301-871215f66351.png)

If you don't have an account, signup on the popup.

Once signed in, it never re-directs your sigin creds to the application. It just sits here:

![image](https://user-images.githubusercontent.com/5581855/150029736-da3cf5d5-76bc-4974-aa93-bdf8a86522d7.png)

**Comment by alexanderson1993** [comment]
This should be fixed now. Reopen if you encounter this issue again.
