### ISSUE TITLE
Can't change crew member count

### ISSUE THREAD

**Issue by miketweaver** [Thorium-Sim/thorium-nova#199]
**Describe the bug**

Cannot change the crew member count

**To Reproduce** Steps to reproduce the behavior:

I have tried both Firefox and Edge.
![msedge_ZY7rwdEGQL](https://user-images.githubusercontent.com/5581855/150031141-6e5a8a1f-09ef-4a12-a5c7-8edbf273f16e.gif)

**Comment by alexanderson1993** [comment]
This is behaving as expected. Currently, there is only a single  station available to be assigned to a ship, so it shouldn't be possible to choose more players than there are stations. Closing.
