### ISSUE TITLE
Ship Theme doesn't get applied

### ISSUE THREAD

**Issue by miketweaver** [Thorium-Sim/thorium-nova#203]
**Describe the bug**
![image](https://user-images.githubusercontent.com/5581855/150040874-d466fc76-7387-46fc-af3f-29648e7126da.png)

**To Reproduce** Steps to reproduce the behavior:

1. Clear cookies/cache on all browsers. 
2. Start nova server with `$ npm run dev`
3. On one browser, open the main page.
4. Start a flight with the defaults
5. In browser 2, open up the app.
6. Assign browser 2 to the pilot position
7. In browser 2 go to the flight lobby, click the home button, go to card development, and open the componentDemo

![image](https://user-images.githubusercontent.com/5581855/150043642-a7e5df9f-5366-4e70-a99c-e7fa5f678157.png)

**Comment by alexanderson1993** [comment]
I believe this has been fixed in the  `develop` branch
