### ISSUE TITLE
Ship Map - Rename decks

### ISSUE THREAD

**Issue by alexanderson1993** [Thorium-Sim/thorium-nova#239]
Make it possible to rename and delete decks in the ship map configuration screen. You can get there from the plugin configuration, in the ships config section. Choose "Ship Map" and it should show a list of decks. 

Right now you can just upload a ship map background, remove the background, add and remove nodes and edges. You can also drag to reorder decks.

 But you cannot rename decks to something like "A Deck" or whatever else you might want to name it. And you cannot delete decks once they have been created.

The rename and delete buttons should either live underneath the decks list, and appear when a deck is selected. Or they should appear underneath the deck map/background upload area. Both are acceptable places.

The rename button should use the prompt function from the  `usePrompt` hook to ask the user for the new name.

The delete button should use the confirm function from the `useConfirm` hook to confirm the user wants to delete the deck.

This might require creating new send procedures in the API layer for renaming and deleting.

![Screenshot 2024-04-23 at 10 19 38 AM](https://github.com/Thorium-Sim/thorium-nova/assets/6558157/72af46cc-ecc4-42a2-af8f-4a370e6b0eb9)

**Comment by ollixx** [comment]
I am on it :-)
