### ISSUE TITLE
Error: Too deep objects in depth 101

### ISSUE THREAD

**Issue by The3gs** [Thorium-Sim/thorium-nova#255]
**Describe the bug**

After cloning from the repo and running, I clicked on the "Start Flight" button, give a name, select a ship, and click start, I immediately see the screen that says

> ***Error
> Too deep objects in depth 101***

The console output is as such:

> [server] Error in request flightPlayerShips: Too deep objects in depth 101
> [server] Error: Too deep objects in depth 101
> [server]     at Encoder.doEncode (/home/bengrant/thorium-nova/node_modules/@msgpack/msgpack/src/Encoder.ts:42:13)
> [server]     at Encoder.encodeMap (/home/bengrant/thorium-nova/node_modules/@msgpack/msgpack/src/Encoder.ts:286:14)
> [server]     at Encoder.encodeObject (/home/bengrant/thorium-nova/node_modules/@msgpack/msgpack/src/Encoder.ts:197:12)
> [server]     at Encoder.doEncode (/home/bengrant/thorium-nova/node_modules/@msgpack/msgpack/src/Encoder.ts:54:12)
> [server]     at Encoder.encodeArray (/home/bengrant/thorium-nova/node_modules/@msgpack/msgpack/src/Encoder.ts:242:12)
> [server]     at Encoder.encodeObject (/home/bengrant/thorium-nova/node_modules/@msgpack/msgpack/src/Encoder.ts:193:12)
> [server]     at Encoder.doEncode (/home/bengrant/thorium-nova/node_modules/@msgpack/msgpack/src/Encoder.ts:54:12)
> [server]     at Encoder.encodeMap (/home/bengrant/thorium-nova/node_modules/@msgpack/msgpack/src/Encoder.ts:286:14)
> [server]     at Encoder.encodeObject (/home/bengrant/thorium-nova/node_modules/@msgpack/msgpack/src/Encoder.ts:197:12)
> [server]     at Encoder.doEncode (/home/bengrant/thorium-nova/node_modules/@msgpack/msgpack/src/Encoder.ts:54:12)

If I return to "http://localhost:3000/" it now shows the buttons `Go To Flight Lobby`, `Go To Card Development`, and `Stop Flight`
`Go To Flight Lobby` returns to an identical error page as before.
`Go To Card Development` opens the list of cards, as I assume it is supposed to, but once I click on one the client sits with a loading icon, and the server crashes with the error:

> [server] /home/bengrant/thorium-nova/node_modules/@msgpack/msgpack/dist/Encoder.js:37
> [server]             throw new Error(`Too deep objects in depth ${depth}`);
> [server]                   ^
> [server] 
> [server] Error: Too deep objects in depth 101
> [server]     at Encoder.doEncode (/home/bengrant/thorium-nova/node_modules/@msgpack/msgpack/src/Encoder.ts:42:13)
> [server]     at Encoder.encodeMap (/home/bengrant/thorium-nova/node_modules/@msgpack/msgpack/src/Encoder.ts:286:14)
> [server]     at Encoder.encodeObject (/home/bengrant/thorium-nova/node_modules/@msgpack/msgpack/src/Encoder.ts:197:12)
> [server]     at Encoder.doEncode (/home/bengrant/thorium-nova/node_modules/@msgpack/msgpack/src/Encoder.ts:54:12)
> [server]     at Encoder.encodeArray (/home/bengrant/thorium-nova/node_modules/@msgpack/msgpack/src/Encoder.ts:242:12)
> [server]     at Encoder.encodeObject (/home/bengrant/thorium-nova/node_modules/@msgpack/msgpack/src/Encoder.ts:193:12)
> [server]     at Encoder.doEncode (/home/bengrant/thorium-nova/node_modules/@msgpack/msgpack/src/Encoder.ts:54:12)
> [server]     at Encoder.encodeMap (/home/bengrant/thorium-nova/node_modules/@msgpack/msgpack/src/Encoder.ts:286:14)
> [server]     at Encoder.encodeObject (/home/bengrant/thorium-nova/node_modules/@msgpack/msgpack/src/Encoder.ts:197:12)
> [server]     at Encoder.doEncode (/home/bengrant/thorium-nova/node_modules/@msgpack/msgpack/src/Encoder.ts:54:12)
> [server] [nodemon] app crashed - waiting for file changes before starting...

**To Reproduce** Steps to reproduce the behavior:

1. Start a Flight as shown in screenshots.

**Expected behavior**

A flight should be started, as well as the server not to crash when the development cards are opened.

**Screenshots**

![image](https://user-images.githubusercontent.com/7924239/158649333-5f510905-bdb3-4af1-9b24-41168cbe8ba9.png)
![image](https://user-images.githubusercontent.com/7924239/158649428-a0ede1c9-20fc-49a6-a7b0-995a8ee5fe1f.png)
![image](https://user-images.githubusercontent.com/7924239/158649499-a3e90259-4fce-4304-ad4b-79529c86cb75.png)
![image](https://user-images.githubusercontent.com/7924239/158649549-ff2f6d60-340c-453b-aa7b-64dab62292c2.png)

**Additional context**

Running on Windows with WSL 2, Ubuntu distribution.
Volta version 1.0.5
npm version 8.1.3
node version 16.13.0

**Comment by alexanderson1993** [comment]
This has been fixed on the  `develop` branch.
