### ISSUE TITLE
☂️ Alpha 8 Umbrella

### ISSUE THREAD

**Issue by alexanderson1993** [Thorium-Sim/thorium-nova#438]
Here's all the things I want to include in Alpha 8. If you want to work on something, convert the checkmark into an issue and assign yourself. Ask in comments or on Discord if you have any questions.

- [x] #439
- [x] #447
- [x] #449
- [x] #469
- [x] #453
- [x] #441
- [x] #451
- [x] #443
- [x] #445
- [x] #467
- [x] #456
- [x] #462
- [x] #454
- [x] #465
- [x] https://github.com/Thorium-Sim/thorium-nova/issues/457
- [x] https://github.com/Thorium-Sim/thorium-nova/issues/458
- [x] #484
- [x] #486
- [x] #488
- [x] #497
- [x] #494
- [x] #501
- [x] #490
- [x] #492
- [x] #504
- [x] #499

I don't know if this is how I want things to go, but it might be interesting to have an even/odd cadence of releases, where odd alphas include major features and even alphas are focused on UI/UX enhancements and bug fixes.

Anything else that should be included? Drop it in.

**Comment by 1deejay** [comment]
I love this, I have an inkling on how to get started on a couple of these things but I'm still a ways out from making big contributions to code.

**Comment by alexanderson1993** [comment]
Take your time, there will always be stuff to do ;) Whenever your ready, just make the issue and assign yourself.

And you might recognize many of these are things you ran into during your usability test - so you've already made a big contribution!

**Comment by 1deejay** [comment]
Yes, I did notice that. Usability tests help drive some focus which is nice.
