### ISSUE TITLE
Stop Flight button hangs the Server

### ISSUE THREAD

**Issue by GlynD02** [Thorium-Sim/thorium-nova#570]
Once a flight has been started on a client click on the Stop Flight button hangs the server with the Reconnecting to Server... message

**To Reproduce** Steps to reproduce the behaviour:

1. Open the client
2. Click on "Start Flight"
3. Choose a mission and start it
4. Click on the "Stop Flight" button

**Expected behaviour**

Server should stop and return to main screen for another mission to be chosen

**Comment by alexanderson1993** [comment]
I'm not able to reproduce this on the current alpha, so we'll say this is fixed. Re-open it if you run into it again.
