### ISSUE TITLE
Viewscreen problem

### ISSUE THREAD

**Issue by GlynD02** [Thorium-Sim/thorium-nova#572]
**Describe the bug**

On the client that is displaying the viewscreen, the view breaks when rotating the ship

**To Reproduce** Steps to reproduce the behaviour:

1. Click on Start Flight > Click Next
2. Click Next on Ship screen
3. Scroll down to Earth Sol mission > Select it > Click Start
4. Choose Viewscreen on Windows client and Pilot in browser
5. Rotate the ship with the Port/Starboard yaw
6. Viewscreen glitches

**Expected behaviour**

Display the viewscreen correctly with no tearing or glitches

**Screenshots**

![image](https://user-images.githubusercontent.com/59927473/221269187-8cfa1788-6f20-4ed5-8d7a-d0ca0a6fd3be.png)

**Additional context**

Win 10, Nvidia 970 graphics card, Client and browser running on same PC

**Comment by GlynD02** [comment]
Did a video as well...

https://user-images.githubusercontent.com/59927473/221271586-9ab17a67-2f53-4fdf-a989-7b9561aaa1ab.mp4

**Comment by alexanderson1993** [comment]
The video is super helpful. It highlights a fun artifact of the way the view screen works. To transition the background image when you move between solar systems, there are two cubes, one slightly smaller than the other, that fade between each other.

The video shows z-buffer fighting between them - your GPU can't decide which one is in front of the other.

There are lots of ways to address this. Not sure which one would be best, and frankly this background has been really annoying to deal with anyway so maybe I'll find a different solution altogether.
