### ISSUE TITLE
Why does logging in with github automatically star this repo?

### ISSUE THREAD

**Issue by Xetera** [Thorium-Sim/thorium-nova#575]
And an invitation to the org??
![image](https://user-images.githubusercontent.com/24978328/222277126-04532eb1-33dc-44b9-95ee-83bc6e72d1c7.png)

I had to double check to make sure the app didn't use the `public_repo` permission (which I didn't know included WRITE permissions too until trying to figure out how the repo got starred in the first place) to overwrite all my repos. Since it behaves so much like a virus.

I don't have a problem with using oauth for starring the repo but that should be made clear before you click login. I'd expect Github to tell me that I was also giving the app permission to star things in the first place but apparently not.

**Comment by alexanderson1993** [comment]
Oh, I forgot that was there. I assure you, there are no malicious intentions. The goal was to make it easy to give folks access to the repo so they could easily contribute.

I'll see about adjusting the UX so you can choose to get an invite to the org and star the repo after logging in.

**Comment by alexanderson1993** [comment]
Auto-starring and auto-inviting has been removed.
