### ISSUE TITLE
RSS feed on website not working

### ISSUE THREAD

**Issue by riidom** [Thorium-Sim/thorium-nova#576]
**Describe the bug**

RSS feed not working

**To Reproduce** Steps to reproduce the behavior:

1. Go to `https://thoriumsim.com/rss.xml`
2. gives a `404 Not Found` with title `Unhandled Thrown Response!`

**Expected behavior**

Working RSS feed for your blog

**Comment by alexanderson1993** [comment]
This has been fixed on the website.
