### ISSUE TITLE
Pilot card fails to load images and says "Your station has experienced an error"

### ISSUE THREAD

**Issue by Froginator45** [Thorium-Sim/thorium-nova#598]
When assigning the Pilot station to a client (within the app or a chrome browser) it will show missing images placeholders in the top corners. And when you login, it overlays the following message over everything in the top left corner "Station Error
Your station has experienced an error. A diagnostic must be performed to restore this station to functionality. Please contact a computer specialist."

**Screenshots**
![image](https://github.com/Thorium-Sim/thorium-nova/assets/19561600/00bfac0a-e244-4614-bdd9-cf63da149789)
![image](https://github.com/Thorium-Sim/thorium-nova/assets/19561600/7f326605-cf49-41a4-b567-348da5963482)

**Additional context**

Running Windows 10 on latest Thorium version: 1.0.0-alpha.11

**Comment by alexanderson1993** [comment]
I believe this was fixed in the latest alpha.
