### ISSUE TITLE
Assigning flight director to station results in error (null)

### ISSUE THREAD

**Issue by Froginator45** [Thorium-Sim/thorium-nova#600]
When assigning the Flight Director station to a client (within the app or a chrome browser) it will load a screen with the background but just say "Error
Cannot read properties of null (reading 'useRef')"

Escape will also not allow you to leave the screen. Need to go back in chrome history.

**Screenshots**
![image](https://github.com/Thorium-Sim/thorium-nova/assets/19561600/cedb2a88-31ab-43d6-818f-434244d60a6c)

**Additional context**

Running Windows 10 on latest Thorium version: 1.0.0-alpha.11

(Love the new randomized background images by the way 😄)

**Comment by alexanderson1993** [comment]
I believe this has been fixed (though not in the latest alpha, just in develop)
