### ISSUE TITLE
Ship map results in a Error (null) message

### ISSUE THREAD

**Issue by Froginator45** [Thorium-Sim/thorium-nova#601]
When editing a ship in the plugins and clicking on "Ship Map" will open a screen with the following message in the top left corner "Error
Cannot read properties of null (reading 'useMemo')"

Must close client and reload to exit view (escape button and reload does not help).

**Screenshots**
![image](https://github.com/Thorium-Sim/thorium-nova/assets/19561600/969e8a32-0d07-454d-90f9-175db5d1586d)

**Additional context**

Running Windows 10 on latest Thorium version: 1.0.0-alpha.11

**Comment by alexanderson1993** [comment]
I believe this has been fixed in the develop branch (though not the latest alpha)
